### ISSUE TITLE
Merge Truck Add/Edit

### ISSUE THREAD

**Issue by ericwilhite** [TAC-Insight/fw-scale-frontend#93] opened 2023-07-14 20:24 UTC
Are there meaningful differences that these screens should be separated? Or can they be merged like Order Add/Edit?
@HaleyBoles

**Comment by HaleyBoles** [comment] 2023-07-14 20:49
> Are there meaningful differences that these screens should be separated? Or can they be merged like Order Add/Edit? @HaleyBoles

Not really many differences between the two, I think we would be able to merge them like Order with little issue

**Comment by HaleyBoles** [comment] 2023-07-14 20:50
Already have a project to-do for it 😄

**Comment by HaleyBoles** [comment] 2023-07-14 20:53
closing as duplicate of 
https://github.com/TAC-Insight/fw-scale-frontend/issues/95

**Closed by HaleyBoles** 2023-07-14 20:53 UTC
